[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
presale = "ALQEfQjpxyXa7xnvakAFf7FmhvJH5xMz3hznMGK7iKXP"
[programs.mainnet]
presale = "ALQEfQjpxyXa7xnvakAFf7FmhvJH5xMz3hznMGK7iKXP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://aged-bitter-card.solana-devnet.quiknode.pro/553cccbe06b94ae764461f7bbdd47334d0e7eb65"
wallet = "/home/harry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 60 # Increase the wait time (in seconds)